Simplify VC++ property setup. Move /EHsc switch to base property sheet, enable conformant mode /permissive- although add the switch /Zc:twoPhase- in order to fix compiler error C2760 in combaseapi.h:229